// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZilEstate.Infrastructure.Persistence;

#nullable disable

namespace ZilEstate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403070732_AddAgencyAndRentalType")]
    partial class AddAgencyAndRentalType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZilEstate.Domain.Entities.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Grand Baie La Croisette, Grand Baie",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Specializing in high-end luxury villas and beachfront estates across Mauritius. Our team of experts provides personalized service to help you find your dream home.",
                            Email = "info@luxurymauritius.mu",
                            IsVerified = true,
                            LogoUrl = "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=200",
                            Name = "Luxury Mauritius Properties",
                            Phone = "+230 5250 1000",
                            Website = "https://luxurymauritius.mu"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ebene Cybercity, Ebene",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Your trusted partner for residential and commercial properties in Mauritius. We cover all districts and offer a wide range of options for every budget.",
                            Email = "contact@paradiseisland.mu",
                            IsVerified = true,
                            LogoUrl = "https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=200",
                            Name = "Paradise Island Real Estate",
                            Phone = "+230 5450 2000",
                            Website = "https://paradiseisland.mu"
                        });
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Port Louis",
                            District = "Port Louis",
                            Latitude = -20.160900000000002,
                            Longitude = 57.497700000000002
                        },
                        new
                        {
                            Id = 2,
                            City = "Curepipe",
                            District = "Plaines Wilhems",
                            Latitude = -20.3156,
                            Longitude = 57.526400000000002
                        },
                        new
                        {
                            Id = 3,
                            City = "Quatre Bornes",
                            District = "Plaines Wilhems",
                            Latitude = -20.2654,
                            Longitude = 57.480400000000003
                        },
                        new
                        {
                            Id = 4,
                            City = "Vacoas-Phoenix",
                            District = "Plaines Wilhems",
                            Latitude = -20.297999999999998,
                            Longitude = 57.4953
                        },
                        new
                        {
                            Id = 5,
                            City = "Rose Hill",
                            District = "Plaines Wilhems",
                            Latitude = -20.239100000000001,
                            Longitude = 57.462899999999998
                        },
                        new
                        {
                            Id = 6,
                            City = "Tamarin",
                            District = "Black River",
                            Latitude = -20.328099999999999,
                            Longitude = 57.376899999999999
                        },
                        new
                        {
                            Id = 7,
                            City = "Flic en Flac",
                            District = "Black River",
                            Latitude = -20.277999999999999,
                            Longitude = 57.368000000000002
                        },
                        new
                        {
                            Id = 8,
                            City = "La Gaulette",
                            District = "Black River",
                            Latitude = -20.497699999999998,
                            Longitude = 57.366199999999999
                        },
                        new
                        {
                            Id = 9,
                            City = "Grand Baie",
                            District = "Rivière du Rempart",
                            Latitude = -20.008700000000001,
                            Longitude = 57.583100000000002
                        },
                        new
                        {
                            Id = 10,
                            City = "Pamplemousses",
                            District = "Pamplemousses",
                            Latitude = -20.098600000000001,
                            Longitude = 57.575600000000001
                        },
                        new
                        {
                            Id = 11,
                            City = "Centre de Flacq",
                            District = "Flacq",
                            Latitude = -20.188300000000002,
                            Longitude = 57.714500000000001
                        },
                        new
                        {
                            Id = 12,
                            City = "Mahébourg",
                            District = "Grand Port",
                            Latitude = -20.407800000000002,
                            Longitude = 57.7029
                        },
                        new
                        {
                            Id = 13,
                            City = "Souillac",
                            District = "Savanne",
                            Latitude = -20.520099999999999,
                            Longitude = 57.5139
                        },
                        new
                        {
                            Id = 14,
                            City = "Moka",
                            District = "Moka",
                            Latitude = -20.2256,
                            Longitude = 57.5381
                        },
                        new
                        {
                            Id = 15,
                            City = "Triolet",
                            District = "Rivière du Rempart",
                            Latitude = -20.057500000000001,
                            Longitude = 57.542000000000002
                        },
                        new
                        {
                            Id = 16,
                            City = "Chamarel",
                            District = "Black River",
                            Latitude = -20.4299,
                            Longitude = 57.387799999999999
                        },
                        new
                        {
                            Id = 17,
                            City = "Goodlands",
                            District = "Rivière du Rempart",
                            Latitude = -19.994299999999999,
                            Longitude = 57.644399999999997
                        },
                        new
                        {
                            Id = 18,
                            City = "Belle Mare",
                            District = "Flacq",
                            Latitude = -20.1919,
                            Longitude = 57.767200000000003
                        },
                        new
                        {
                            Id = 19,
                            City = "Blue Bay",
                            District = "Grand Port",
                            Latitude = -20.448,
                            Longitude = 57.714799999999997
                        },
                        new
                        {
                            Id = 20,
                            City = "Terre Rouge",
                            District = "Pamplemousses",
                            Latitude = -20.145600000000002,
                            Longitude = 57.550800000000002
                        });
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int?>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<bool?>("Furnished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("MinimumStayDays")
                        .HasColumnType("integer");

                    b.Property<int?>("Parking")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PricePerNight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PricePerWeek")
                        .HasColumnType("numeric");

                    b.Property<int>("RentalType")
                        .HasColumnType("integer");

                    b.Property<string>("SellerEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SellerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SellerWhatsApp")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("SizeArpents")
                        .HasColumnType("double precision");

                    b.Property<double?>("SizeM2")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsApproved");

                    b.HasIndex("LocationId");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgencyId = 1,
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CreatedAt = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stunning 4-bedroom villa with private pool and sea view. Perfect for families looking for luxury living in the north of Mauritius.",
                            Furnished = true,
                            IsApproved = true,
                            IsFeatured = true,
                            Latitude = -20.008700000000001,
                            LocationId = 9,
                            Longitude = 57.583100000000002,
                            Parking = 2,
                            Price = 15000000m,
                            RentalType = 0,
                            SellerEmail = "jmdupont@email.com",
                            SellerName = "Jean-Marc Dupont",
                            SellerPhone = "+230 5742 8834",
                            SellerWhatsApp = "+23057428834",
                            SizeM2 = 350.0,
                            Status = 0,
                            Title = "Luxury Villa in Grand Baie",
                            Type = 1,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 2,
                            AgencyId = 2,
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CreatedAt = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bright 2-bedroom apartment on the 3rd floor with balcony. Close to supermarkets, schools, and the city center.",
                            Furnished = false,
                            IsApproved = true,
                            IsFeatured = true,
                            Latitude = -20.2654,
                            LocationId = 3,
                            Longitude = 57.480400000000003,
                            Parking = 1,
                            Price = 3500000m,
                            RentalType = 0,
                            SellerEmail = "priya.r@email.com",
                            SellerName = "Priya Ramgoolam",
                            SellerPhone = "+230 5251 9012",
                            SellerWhatsApp = "+23052519012",
                            SizeM2 = 85.0,
                            Status = 0,
                            Title = "Modern Apartment in Quatre Bornes",
                            Type = 2,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 3,
                            AgencyId = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rare 15-arpent plot with panoramic sea view in the exclusive Tamarin area. Building permit available.",
                            IsApproved = true,
                            IsFeatured = false,
                            Latitude = -20.328099999999999,
                            LocationId = 6,
                            Longitude = 57.376899999999999,
                            Price = 8500000m,
                            RentalType = 0,
                            SellerName = "Antoine Leclercq",
                            SellerPhone = "+230 5888 2345",
                            SellerWhatsApp = "+23058882345",
                            SizeArpents = 15.0,
                            Status = 0,
                            Title = "Land Plot in Tamarin - Sea View",
                            Type = 3,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 4,
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CreatedAt = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spacious 3-bedroom house available for long-term rental. Quiet neighborhood, fully furnished, with garden and covered parking.",
                            Furnished = true,
                            IsApproved = true,
                            IsFeatured = true,
                            Latitude = -20.3156,
                            LocationId = 2,
                            Longitude = 57.526400000000002,
                            Parking = 1,
                            Price = 35000m,
                            RentalType = 0,
                            SellerEmail = "mc.bonnefoy@email.com",
                            SellerName = "Marie-Claire Bonnefoy",
                            SellerPhone = "+230 5314 6789",
                            SizeM2 = 200.0,
                            Status = 1,
                            Title = "House for Rent in Curepipe",
                            Type = 0,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 5,
                            AgencyId = 2,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Prime commercial space in the heart of Port Louis business district. Ground floor, high visibility, ideal for retail or office.",
                            IsApproved = true,
                            IsFeatured = false,
                            Latitude = -20.160900000000002,
                            LocationId = 1,
                            Longitude = 57.497700000000002,
                            Price = 45000m,
                            RentalType = 0,
                            SellerEmail = "karim.b@business.mu",
                            SellerName = "Karim Bhunjun",
                            SellerPhone = "+230 5456 7890",
                            SellerWhatsApp = "+23054567890",
                            SizeM2 = 120.0,
                            Status = 1,
                            Title = "Commercial Space in Port Louis",
                            Type = 4,
                            ViewCount = 0
                        },
                        new
                        {
                            Id = 6,
                            AgencyId = 1,
                            Bathrooms = 4,
                            Bedrooms = 5,
                            CreatedAt = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Exceptional beachfront villa with direct beach access. 5 bedrooms, private infinity pool, fully equipped kitchen and outdoor BBQ area.",
                            Furnished = true,
                            IsApproved = true,
                            IsFeatured = true,
                            Latitude = -20.277999999999999,
                            LocationId = 7,
                            Longitude = 57.368000000000002,
                            Parking = 3,
                            Price = 25000000m,
                            RentalType = 0,
                            SellerEmail = "sophie.b@lux.mu",
                            SellerName = "Sophie Bertrand",
                            SellerPhone = "+230 5567 2345",
                            SellerWhatsApp = "+23055672345",
                            SizeM2 = 500.0,
                            Status = 0,
                            Title = "Beachfront Villa in Flic en Flac",
                            Type = 1,
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPrimary = true,
                            PropertyId = 1,
                            Url = "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"
                        },
                        new
                        {
                            Id = 2,
                            IsPrimary = false,
                            PropertyId = 1,
                            Url = "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800"
                        },
                        new
                        {
                            Id = 3,
                            IsPrimary = true,
                            PropertyId = 2,
                            Url = "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"
                        },
                        new
                        {
                            Id = 4,
                            IsPrimary = false,
                            PropertyId = 2,
                            Url = "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"
                        },
                        new
                        {
                            Id = 5,
                            IsPrimary = true,
                            PropertyId = 3,
                            Url = "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"
                        },
                        new
                        {
                            Id = 6,
                            IsPrimary = true,
                            PropertyId = 4,
                            Url = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800"
                        },
                        new
                        {
                            Id = 7,
                            IsPrimary = true,
                            PropertyId = 5,
                            Url = "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800"
                        },
                        new
                        {
                            Id = 8,
                            IsPrimary = true,
                            PropertyId = 6,
                            Url = "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"
                        },
                        new
                        {
                            Id = 9,
                            IsPrimary = false,
                            PropertyId = 6,
                            Url = "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800"
                        });
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.PropertyQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.Property", b =>
                {
                    b.HasOne("ZilEstate.Domain.Entities.Agency", "Agency")
                        .WithMany("Properties")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ZilEstate.Domain.Entities.Location", "Location")
                        .WithMany("Properties")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ZilEstate.Domain.Entities.User", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.PropertyImage", b =>
                {
                    b.HasOne("ZilEstate.Domain.Entities.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.PropertyQuestion", b =>
                {
                    b.HasOne("ZilEstate.Domain.Entities.Property", "Property")
                        .WithMany("Questions")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.Review", b =>
                {
                    b.HasOne("ZilEstate.Domain.Entities.Property", "Property")
                        .WithMany("Reviews")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.User", b =>
                {
                    b.HasOne("ZilEstate.Domain.Entities.Agency", "Agency")
                        .WithMany("Agents")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.Agency", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.Location", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Questions");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ZilEstate.Domain.Entities.User", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
